### ISSUE TITLE
Suggest change title to NetApp Active IQ Classic Documentation to differentiate from Active IQ Digital Advisor

### ISSUE THREAD

**Issue by JetMaurier** [NetAppDocs/active-iq-1#8]
Page: [NetApp Active IQ Documentation](https://docs.netapp.com/us-en/active-iq-1/index.html)

**Comment by netapp-manishc** [comment]
The title of the Active IQ classic documentation is Active IQ documentation and the title of the Active IQ Digital Advisor documentation is Active IQ Digital Advisor Documentation. 
Active IQ documentation: https://docs.netapp.com/us-en/active-iq-1/
Active IQ Digital Advisor Documentation: https://docs.netapp.com/us-en/active-iq/
